language: bash

services:
  - docker

sudo: required
branches:
  only:
    - master
before_script:
  # 登录到 docker hub  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t zyhcool/travistest /var/src/travis-test

after_success:
  - docker push zyhcool/cicdtest:latest
  