# 单体部署
version: '3.7'
services:
  web:
    build: .
    image: cicd-test
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/authfile/auth.json
    volumes:
      - /var/authfile/auth.json:/var/authfile/auth.json
    ports:
      - 4000:4000
    networks:
      - cicd-web-net
networks:
  cicd-web-net:
    driver: bridge
